platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'wenwen' do
    project 'wenwen.xcodeproj'
    pod 'Alamofire', '~> 4.3'
    pod 'SwiftyJSON', '~> 3.1'
    pod 'IQKeyboardManager', '~> 4.0'
    pod 'MJRefresh', '~> 3.0.8'
    pod 'SnapKit', '~> 4.0.0'
    pod 'Kingfisher', '~> 4.0'
    pod 'YYCache', '~> 1.0'
    pod 'YYCategories'
    pod 'SVProgressHUD'
    pod 'iCarousel'
    pod 'YYText'
    pod 'YYImage'
end
